### ISSUE TITLE
Add DMX to Interfaces section

### ISSUE THREAD

**Issue by Zergud** [globallightingdata/gldf#1]
Propose to add 2 items to ControlGear\Interfaces

1. DMX - for unidirectional DMX supported device
2. DMX (RDM) - with RDM support

**Comment by Kurpanik** [comment]
Hello and thank you for the suggestion. We will discuss this at our next round and take it into account.

**Comment by Kurpanik** [comment]
We have just discussed this and will add the two values in the upcoming version

**Comment by Kurpanik** [comment]
Released in [v0.9-beta.4](https://github.com/globallightingdata/gldf/releases/tag/v0.9-beta.4)
