### ISSUE TITLE
Pixel Count

### ISSUE THREAD

**Issue by Zergud** [globallightingdata/gldf#2]
For dynamically controlled luminaires we need information about the number of pixels
Its not the same as different LightSource
often there is single luminous surface and photometry information given for the device as a whole (all pixels are white)

just for example: 
https://www.martin.com/en/products/tripix-300-and-1200
software view:
![изображение](https://user-images.githubusercontent.com/869819/117414873-52544200-af20-11eb-80d7-80b2ebd9950b.png)

**Comment by Kurpanik** [comment]
We will discuss this as well. However, even if this is not "hardcoded" into the format (yet?), there is always the possibility to use the `CustomProperties` for additional information like yours:

```xml
<ProductMetaData>
  <ProductNumber>
    <Locale language="en">Tripix 1200 RGB</Locale>
  </ProductNumber>
  <ProductName>
    <Locale language="en">IP66 rated LED strips using tricolor LEDs</Locale>
  </ProductName>
  <DescriptiveAttributes>
    <CustomProperties>
      <Property id="pixelCount">
        <Name>
          <Locale language="en">Pixel count</Locale>
        </Name>
        <Value>4</Value>
      </Property>
    </CustomProperties>
  </DescriptiveAttributes>
</ProductMetaData>
```

**Comment by Zergud** [comment]
I agree, may be its not an issue and you solution is prety good for me
But, for versatility, I propose to include in the format with default value 1

this is a simple case, for more complex case I will open discussion in Ideas

**Comment by Kurpanik** [comment]
Yes, we have decided to keep this as a possible custom property. This is exactly what they are meant for.
